sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - 1.22.1
  - 1.23.0
  - stable

cache:
  cargo: true

addons:
  apt:
    packages:
    - libdbus-1-dev
    - pkg-config
    - sqlite

script:
  - |
    bash ./scripts/find-dead-symlinks || exit 1
    bash ./scripts/license-headers-updated || exit 1
    cargo build --all --all-features -j 1 || exit 1
    cargo test  --all --all-features -j 1 || exit 1

notifications:
  email:
    on_success: never
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"

