[package]
name = "imag-wiki"
version = "0.7.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-wiki command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
log = "0.3"
toml = "0.4"
toml-query = "^0.4"
is-match = "0.1"
version = "2.0.1"

libimagentrycategory = { version = "0.7.0", path = "../../../lib/entry/libimagentrycategory" }
libimagentryedit     = { version = "0.7.0", path = "../../../lib/entry/libimagentryedit" }
libimagentrylink     = { version = "0.7.0", path = "../../../lib/entry/libimagentrylink" }
libimagentrymarkdown = { version = "0.7.0", path = "../../../lib/entry/libimagentrymarkdown" }
libimagentrytag      = { version = "0.7.0", path = "../../../lib/entry/libimagentrytag" }
libimagentryview     = { version = "0.7.0", path = "../../../lib/entry/libimagentryview" }
libimagerror         = { version = "0.7.0", path = "../../../lib/core/libimagerror" }
libimagrt            = { version = "0.7.0", path = "../../../lib/core/libimagrt" }
libimagwiki          = { version = "0.7.0", path = "../../../lib/domain/libimagwiki" }

